version: "3.8"
services:
  front-v2:
    image: xfenix/xfenix-ru-front-v2:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/srv/certificates
      - challenge_mount:/var/www/certbot
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot:v1.20.0
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - challenge_mount:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot certonly -d xfenix.ru --non-interactive --agree-tos --webroot --webroot-path /var/www/certbot/; sleep 12h & wait $${!}; done;'"
  back:
    image: xfenix/xfenix-ru-back:latest
    env_file: .env
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
volumes:
  challenge_mount:
