version: "3"
services:
  front-v2:
    image: xfenix/xfenix-ru-front-v2:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /srv/www/xfenix-v2.ru/.well-known:/srv/www/.well-known
    links:
      - back
  back:
    image: xfenix/xfenix-ru-back:latest
    env_file: .env
