version: "3"
services:
  front-v2:
    image: xfenix/xfenix-ru-front-v2:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
  back:
    image: xfenix/xfenix-ru-back:latest
    env_file: .env
