name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check Out Repo
  #       uses: actions/checkout@v2

  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKER_HUB_USERNAME }}
  #         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1

  #     - name: Build and push front
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: ./front-v2
  #         push: true
  #         tags: ${{ secrets.DOCKER_HUB_USERNAME }}/xfenix-ru-front-v2:latest

  #     - name: Build and push back
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: ./back
  #         push: true
  #         tags: ${{ secrets.DOCKER_HUB_USERNAME }}/xfenix-ru-back:latest

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo "${{ secrets.SSH_PRIVATE_KEY }}" >> ~/.ssh/id_rsas
          echo ssh ${{ secrets.XFENIXRU_USER }}@xfenix.ru -p${{secrets.XFENIXRU_PORT}} -t "sudo docker ps"
